// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avater.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace protos {
  public static partial class Position
  {
    static readonly string __ServiceName = "avater.Position";

    static readonly grpc::Marshaller<global::protos.GetRequest> __Marshaller_avater_GetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::protos.GetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::protos.GetResponse> __Marshaller_avater_GetResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::protos.GetResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::protos.UpdateRequest> __Marshaller_avater_UpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::protos.UpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::protos.UpdateResponse> __Marshaller_avater_UpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::protos.UpdateResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::protos.GetRequest, global::protos.GetResponse> __Method_Get = new grpc::Method<global::protos.GetRequest, global::protos.GetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_avater_GetRequest,
        __Marshaller_avater_GetResponse);

    static readonly grpc::Method<global::protos.UpdateRequest, global::protos.UpdateResponse> __Method_Update = new grpc::Method<global::protos.UpdateRequest, global::protos.UpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Update",
        __Marshaller_avater_UpdateRequest,
        __Marshaller_avater_UpdateResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::protos.AvaterReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Position</summary>
    public abstract partial class PositionBase
    {
      public virtual global::System.Threading.Tasks.Task<global::protos.GetResponse> Get(global::protos.GetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::protos.UpdateResponse> Update(global::protos.UpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Position</summary>
    public partial class PositionClient : grpc::ClientBase<PositionClient>
    {
      /// <summary>Creates a new client for Position</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PositionClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Position that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PositionClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PositionClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PositionClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::protos.GetResponse Get(global::protos.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::protos.GetResponse Get(global::protos.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::protos.GetResponse> GetAsync(global::protos.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::protos.GetResponse> GetAsync(global::protos.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      public virtual global::protos.UpdateResponse Update(global::protos.UpdateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Update(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::protos.UpdateResponse Update(global::protos.UpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Update, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::protos.UpdateResponse> UpdateAsync(global::protos.UpdateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::protos.UpdateResponse> UpdateAsync(global::protos.UpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Update, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PositionClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PositionClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PositionBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_Update, serviceImpl.Update).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PositionBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Get, serviceImpl.Get);
      serviceBinder.AddMethod(__Method_Update, serviceImpl.Update);
    }

  }
}
#endregion
